package ua.kvitkovo.notifications;

public enum NotificationType {
    MAIL_CONFIRMATION,
    MAIL_CONFIRMATION_SUCCESSFULLY,
    RESET_PASSWORD,
    CHANGE_PASSWORD,
    CREATE_NEW_USER,
    REGISTER_BY_GOOGLE,
    ANSWER_FEEDBACK_MESSAGE,
    NEW_ORDER
}
