const ROUTES = {
  home: '/',
  promotions: '/promotions',
  about: '/about',
  delivery: '/delivery',
  contacts: '/contacts',
  partner: '/partner',
  privacy: '/privacy',
  orderStatus: '/orderStatus',
  care: '/care',
  faq: '/faq',
  account: '/account',
  changeDetails: '/account/change-details',
  changePassword: '/account/change-password',
  orders: '/account/orders',
  card: '/product/:myId',
  emailConfirmation: '/user/email/:code/confirm/',
  category: '/category',
  order: '/order',
  placedOrder: '/order/:orderNumber',
  passwordReset: '/user/resetPassword/:code',
  specificCategory: '/categories/:categoryId',
  search: '/search/:query',
  decor: '/decor',
};

export default ROUTES;
